CITY_TO_COUNTRY = {
    'Aberdeen': 'Scotland',
    'Abu Dhabi': 'United Arab Emirates',
    'Adelaide': 'Australia',
    'Ahmedabad': 'India',
    'Al Amarat': 'Oman',
    'Amstelveen': 'Netherlands',
    'Antigua': 'Antigua and Barbuda',
    'Auckland': 'New Zealand',
    'Ayr': 'Scotland',
    'Bangalore': 'India',
    'Barbados': 'Barbados',
    'Belfast': 'Northern Ireland',
    'Bengaluru': 'India',
    'Benoni': 'South Africa',
    'Birmingham': 'England',
    'Bloemfontein': 'South Africa',
    'Bogra': 'Bangladesh',
    'Bready': 'Ireland',
    'Bridgetown': 'Barbados',
    'Brisbane': 'Australia',
    'Bristol': 'England',
    'Bulawayo': 'Zimbabwe',
    'Cairns': 'Australia',
    'Canberra': 'Australia',
    'Canterbury': 'New Zealand',
    'Cape Town': 'South Africa',
    'Cardiff': 'Wales',
    'Centurion': 'South Africa',
    'Chandigarh': 'India',
    'Chattogram': 'Bangladesh',
    'Chennai': 'India',
    'Chester-le-Street': 'England',
    'Chittagong': 'Bangladesh',
    'Christchurch': 'New Zealand',
    'Colombo': 'Sri Lanka',
    'Cuttack': 'India',
    'Dambulla': 'Sri Lanka',
    'Darwin': 'Australia',
    'Dehra Dun': 'India',
    'Delhi': 'India',
    'Deventer': 'Netherlands',
    'Dhaka': 'Bangladesh',
    'Dharamsala': 'India',
    'Dharmasala': 'India',
    'Doha': 'Qatar',
    'Dominica': 'Dominica',
    'Dubai': 'United Arab Emirates',
    'Dublin': 'Ireland',
    'Dunedin': 'New Zealand',
    'Durban': 'South Africa',
    'East London': 'South Africa',
    'Edinburgh': 'Scotland',
    'Faisalabad': 'Pakistan',
    'Faridabad': 'India',
    'Fatullah': 'Bangladesh',
    'Galle': 'Sri Lanka',
    'Glasgow': 'Scotland',
    'Gqeberha': 'South Africa',
    'Greater Noida': 'India',
    'Grenada': 'Grenada',
    'Gros Islet': 'Saint Lucia',
    'Guwahati': 'India',
    'Guyana': 'Guyana',
    'Gwalior': 'India',
    'Hambantota': 'Sri Lanka',
    'Hamilton': 'New Zealand',
    'Harare': 'Zimbabwe',
    'Hobart': 'Australia',
    'Hong Kong': 'Hong Kong',
    'Hyderabad': 'India',
    'Indore': 'India',
    'Jaipur': 'India',
    'Jamaica': 'Jamaica',
    'Jamshedpur': 'India',
    'Johannesburg': 'South Africa',
    'Kandy': 'Sri Lanka',
    'Kanpur': 'India',
    'Karachi': 'Pakistan',
    'Kathmandu': 'Nepal',
    'Khulna': 'Bangladesh',
    'Kimberley': 'South Africa',
    'King City': 'Canada',
    'Kingston': 'Jamaica',
    'Kingstown': 'Saint Vincent and the Grenadines',
    'Kirtipur': 'Nepal',
    'Kochi': 'India',
    'Kolkata': 'India',
    'Kuala Lumpur': 'Malaysia',
    'Lahore': 'Pakistan',
    'Lauderhill': 'United States',
    'Leeds': 'England',
    'Lincoln': 'New Zealand',
    'London': 'England',
    'Lucknow': 'India',
    'Manchester': 'England',
    'Margao': 'India',
    'Melbourne': 'Australia',
    'Mirpur': 'Bangladesh',
    'Mombasa': 'Kenya',
    'Mount Maunganui': 'New Zealand',
    'Multan': 'Pakistan',
    'Mumbai': 'India',
    'Nagpur': 'India',
    'Nairobi': 'Kenya',
    'Napier': 'New Zealand',
    'Nelson': 'New Zealand',
    'North Sound': 'Antigua and Barbuda',
    'Nottingham': 'England',
    'Paarl': 'South Africa',
    'Pallekele': 'Sri Lanka',
    'Pearland': 'United States',
    'Perth': 'Australia',
    'Peshawar': 'Pakistan',
    'Pietermaritzburg': 'South Africa',
    'Port Elizabeth': 'South Africa',
    'Port Moresby': 'Papua New Guinea',
    'Port of Spain': 'Trinidad and Tobago',
    'Potchefstroom': 'South Africa',
    'Providence': 'Guyana',
    'Pune': 'India',
    'Queenstown': 'New Zealand',
    'Raipur': 'India',
    'Rajkot': 'India',
    'Ranchi': 'India',
    'Rawalpindi': 'Pakistan',
    'Rotterdam': 'Netherlands',
    'Sharjah': 'United Arab Emirates',
    'Sheikhupura': 'Pakistan',
    'Sind': 'Pakistan',
    'Southampton': 'England',
    'St Kitts': 'Saint Kitts and Nevis',
    'St Lucia': 'Saint Lucia',
    'St Vincent': 'Saint Vincent and the Grenadines',
    'Sydney': 'Australia',
    'Sylhet': 'Bangladesh',
    'Taunton': 'England',
    'Thiruvananthapuram': 'India',
    'Toronto': 'Canada',
    'Townsville': 'Australia',
    'Trinidad': 'Trinidad and Tobago',
    'Utrecht': 'Netherlands',
    'Vadodara': 'India',
    'Visakhapatnam': 'India',
    'Wellington': 'New Zealand',
    'Whangarei': 'New Zealand',
    'Windhoek': 'Namibia',
    "St George's": "Grenada",
}
