VENUE_TO_CITY = {
    'Abu Dhabi': 'Abu Dhabi',
    'Adelaide Oval': 'Adelaide',
    'Al Amarat': 'Al Amarat',
    'Bulawayo Athletic Club': 'Bulawayo',
    'Cape Town': 'Cape Town',
    'Chittagong Divisional Stadium': 'Chittagong',
    'Dehra Dun': 'Dehra Dun',
    'Dubai International Cricket Stadium': 'Dubai',
    'Dubai Sports City Cricket Stadium': 'Dubai',
    'East London': 'East London',
    'Galle International Stadium': 'Galle',
    'Greater Noida': 'Greater Noida',
    'Gros Islet': 'Gros Islet',
    'Harare Sports Club': 'Harare',
    'Hong Kong': 'Hong Kong',
    'King City': 'King City',
    'Kuala Lumpur': 'Kuala Lumpur',
    'Melbourne Cricket Ground': 'Melbourne',
    'Mombasa Sports Club Ground': 'Mombasa',
    'Mount Maunganui': 'Mount Maunganui',
    'Multan Cricket Stadium': 'Multan',
    'North Sound': 'North Sound',
    'Pallekele International Cricket Stadium': 'Pallekele',
    'Perth Stadium': 'Perth',
    'Port Elizabeth': 'Port Elizabeth',
    'Port Moresby': 'Port Moresby',
    'Port of Spain': 'Port of Spain',
    'Queenstown Events Centre': 'Queenstown',
    'Rangiri Dambulla International Stadium': 'Dambulla',
    'Rawalpindi Cricket Stadium': 'Rawalpindi',
    'Sharjah Cricket Association Stadium': 'Sharjah',
    'Sharjah Cricket Stadium': 'Sharjah',
    'Sheikhupura Stadium': 'Sheikhupura',
    'St Kitts': 'St Kitts',
    'St Lucia': 'St Lucia',
    'St Vincent': 'St Vincent',
    'Sydney Cricket Ground': 'Sydney',
    "St George's": "St George's",
}
